export const GAME_CONSTANTS = {
    MAX_PLAYERS: 100,
    MAX_HEALTH: 100,
    MAX_MANA: 100,
    STARTING_LEVEL: 1,
    STARTING_EXPERIENCE: 0,
    EXPERIENCE_PER_LEVEL: 100,
    COMBAT_TIMEOUT: 300, // in seconds
    ITEM_LIMIT: 50,
    DEFAULT_CHARACTER_NAME: "Adventurer",
    DEFAULT_ACCOUNT_ROLE: "Player",
};